### ISSUE TITLE
Customer support system

### ISSUE THREAD

**Issue by JoelSanchez** [JoelSanchez/ventas#6]
Allow users to ask questions to the store.
Task includes administration section (list pending questions and past threads) and frontoffice section (customer support button that sends the user to the customer support page, which has a form that lets him/her contact the store).
See other ecommerce platforms for references.

**Comment by tapas4you** [comment]
Hi JoelSanchez,
When i run lein repl i found following error so please guide me what to do so that i can resolve it.

Could not find artifact com.datomic:datomic-pro:jar:0.9.5697 in central (https://repo1.maven.org/maven2/)
Could not find artifact com.datomic:datomic-pro:jar:0.9.5697 in clojars (https://repo.clojars.org/)
Could not transfer artifact com.datomic:datomic-pro:jar:0.9.5697 from/to my.datomic.com (https://my.datomic.com/repo): Not authorized , ReasonPhrase:Unauthorized.
Could not find artifact com.datomic:datomic-pro:jar:0.9.5697 in releases (https://repo.clojars.org)
Could not find artifact com.datomic:datomic-pro:jar:0.9.5697 in snapshots (https://repo.clojars.org)
Could not transfer artifact com.datomic:datomic-pro:pom:0.9.5697 from/to my.datomic.com (https://my.datomic.com/repo): Not authorized , ReasonPhrase:Unauthorized.
This could be due to a typo in :dependencies, file system permissions, or network issues.
If you are behind a proxy, try setting the 'http_proxy' environment variable.
Exception in thread "Thread-1" clojure.lang.ExceptionInfo: Could not resolve dependencies {:suppress-msg true, :exit-code 1}
	at clojure.core$ex_info.invokeStatic(core.clj:4617)
	at clojure.core$ex_info.invoke(core.clj:4617)
	at leiningen.core.classpath$get_dependencies_STAR_.invokeStatic(classpath.clj:311)
	at leiningen.core.classpath$get_dependencies_STAR_.invoke(classpath.clj:265)
	at clojure.lang.AFn.applyToHelper(AFn.java:165)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:646)
	at clojure.core$memoize$fn__5708.doInvoke(core.clj:6107)
	at clojure.lang.RestFn.invoke(RestFn.java:457)
	at leiningen.core.classpath$get_dependencies$fn__3861.invoke(classpath.clj:332)
	at leiningen.core.classpath$get_dependencies.invokeStatic(classpath.clj:330)
	at leiningen.core.classpath$get_dependencies.doInvoke(classpath.clj:324)
	at clojure.lang.RestFn.invoke(RestFn.java:445)
	at clojure.lang.AFn.applyToHelper(AFn.java:160)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at clojure.core$apply.invokeStatic(core.clj:652)
	at clojure.core$apply.invoke(core.clj:641)
	at leiningen.core.classpath$resolve_managed_dependencies.invokeStatic(classpath.clj:443)
	at leiningen.core.classpath$resolve_managed_dependencies.doInvoke(classpath.clj:430)
	at clojure.lang.RestFn.invoke(RestFn.java:445)
	at leiningen.core.eval$prep.invokeStatic(eval.clj:85)
	at leiningen.core.eval$prep.invoke(eval.clj:73)
	at leiningen.core.eval$eval_in_project.invokeStatic(eval.clj:363)
	at leiningen.core.eval$eval_in_project.invoke(eval.clj:357)
	at leiningen.repl$server$fn__5963.invoke(repl.clj:278)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:646)
	at clojure.core$with_bindings_STAR_.invokeStatic(core.clj:1881)
	at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1881)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at clojure.core$apply.invokeStatic(core.clj:650)
	at clojure.core$bound_fn_STAR_$fn__4671.doInvoke(core.clj:1911)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by JoelSanchez** [comment]
Yes, you need to define DATOMIC__USERNAME and DATOMIC__PASSWORD, otherwise Leiningen won't be able to download datomic from the datomic repo. Remember that these credentials are not the same as your login credentials: you need to use your email as the user and your "download key" (shown in https://my.datomic.com/account) as the password.
